name: clean_flutter_app
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # cupertino_icons: ^0.1.3
  http: 0.12.2

dev_dependencies:
  # flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  faker: 1.3.0
  mockito: 3.0.2
  test: 1.15.0

flutter:
  uses-material-design: true
